<?xml version="1.0"?>
<robot name="gvrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find gvrbot)/models/urdf/inertial_tensors.urdf.xacro" />

  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="0.262" />
  <xacro:property name="track" value="0.37559" />
  <xacro:property name="wheel_vertical_offset" value="0.03" />
  <xacro:property name="footprint_vertical_offset" value="-0.0655" />

  <xacro:property name="wheel_radius" value="0.098" />
  <xacro:property name="wheel_width" value="0.040" />

  <xacro:property name="chassis_length" value="0.680" />
  <xacro:property name="chassis_width" value="0.42" />
  <xacro:property name="chassis_height" value="0.178" />
  <xacro:property name="chassis_mass" value="10.89" />
  
  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120" />

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>

  <xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${prefix}_wheel_link">
    <!-- 
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://jackal_description/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      -->
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <selfCollide>false</selfCollide>
      <mu1 value="0.5"/>
      <mu2 value="0.5"/>
      <kp value="10000000.0" />
      <kd value="1" />
      <fdir1 value="1 0 0"/>
    </gazebo>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

    <!-- In reality, gvrbot has only two motors, one per side. However, it's more
         straightforward for Gazebo to simulate as if there's an actuator per wheel. -->
    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:wheel prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" />      
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>  
  </link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis_link" />
  </joint>

  <link name="chassis_link">
    <visual>
      <origin xyz="0.35 0 ${footprint_vertical_offset}" rpy="${PI} ${PI} -${PI/2}"/>
      <geometry>
        <mesh filename="package://gvrbot/models/meshes/gvrbot_base.STL"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
            <origin xyz="0.35 0 ${footprint_vertical_offset}" rpy="${PI} ${PI} -${PI/2}"/>
      <geometry>
        <mesh filename="package://gvrbot/models/meshes/gvrbot_base.STL"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Center of mass -->
        <origin xyz="-0.005 0 0.03" rpy="0 0 0" />
        <mass value="${chassis_mass}"/>
      <!-- Moments of inertia: ( chassis without wheels ) -->
      <xacro:box_inertia x="${chassis_length}" y="${chassis_width}" z="${chassis_height}" mass="${chassis_mass}" />
    </inertial>
  </link>

 <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="imu_link" />
  </joint>
  
  
  <!-- Create a mount point in the center of top plate -->
  <link name="top_mount"></link>
  <joint name="top_mount_joint" type="fixed">
    <parent link="base_link" />
    <child link="top_mount" />
    <origin xyz="-0.004 0 0.406" />
  </joint>

  <!-- Add GPS to top left of top plate on robot. -->
  <link name="navsat_link">
    <visual>
      <geometry>
        <cylinder radius="0.026" length="0.016" />
      </geometry>
      <origin xyz="0 0 0" />
      <material name="black" />
    </visual>
  </link>
  <joint name="navsat_joint" type="fixed">
        <parent link="top_mount" />
    <child link="navsat_link" />
    <origin xyz="-0.1 0.1 0" />
  </joint>

  <!-- Add Hokuyo UST10 2d Lidar to front of robot.  -->
      <xacro:include filename="$(find gvrbot)/models/urdf/hokuyo_ust10.urdf.xacro" />
      <xacro:hokuyo_ust10_mount prefix="top"  topic="front/scan"/>
      <joint name="top_laser_mount_joint" type="fixed">
        <origin xyz="0.1 0 0" rpy="0 0 0" />
        <parent link="top_mount" />
        <child link="top_laser_mount" />
      </joint>

  <!-- Bring in simulation data for Gazebo.   -->
  <xacro:include filename="$(find gvrbot)/models/urdf/gvrbot.gazebo" />

  <!-- Add 8020 Frame.  -->
    <xacro:include filename="$(find gvrbot)/models/urdf/frame_8020.urdf.xacro" />    
    <xacro:frame_8020 parent="base_link" offset_x="-0.335" offset_y="-0.117" offset_z="0.132"/>
  
  
  <!-- Add D435 Depth Sensor.   -->
    <xacro:arg name="use_nominal_extrinsics" default="true"/>
  <xacro:include filename="$(find gvrbot)/models/urdf/_d435.urdf.xacro" />   
  
  <xacro:sensor_d435 parent="top_mount" use_nominal_extrinsics="$(arg use_nominal_extrinsics)">
    <origin xyz="0.14 0 -0.04" rpy="0 0 0"/>
  </xacro:sensor_d435>

  
  

</robot>
